=== Llorens1982/ASIR/1º Lenguajes de marcas y sistemas de gestión de información/EXAMEN EXTRAODINARIO/DTD/horario.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT horario (entrenamiento,plantilla)>
<!ELEMENT entrenamiento (entrenador,tiempo)>
<!ELEMENT plantilla (jugador)+>
<!ELEMENT entrenador (#PCDATA)>
<!ELEMENT tiempo (#PCDATA)>
<!ELEMENT jugador (nombre,dorsal)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT dorsal (#PCDATA)>

<!ATTLIST horario dia CDATA>
<!ATTLIST entrenamiento tipo CDATA>
<!ATTLIST tiempo medidas CDATA>
<!ATTLIST jugador pos (portero|defensa|medio|delantero) #REQUIRED>
<!ATTLIST jugador ID #REQUIRED>

=== Llorens1982/ASIR/1º Lenguajes de marcas y sistemas de gestión de información/EXAMEN EXTRAODINARIO/DTD/horario.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alumnes SYSTEM "horario.dtd">
<horario dia="26-6-2017">
  <entrenamiento tipo="resistencia">
    <entrenador>Robert</entrenador>
    <tiempo medida="minutos">60</tiempo>
  </entrenamiento>
  <plantilla>
    <jugador pos="portero" id="J001">
      <nombre>Pedro</nombre>
      <dorsal>1</dorsal>
    </jugador>
    <jugador pos="medio" id="J021">
      <nombre>Juan</nombre>
      <dorsal>21</dorsal>
    </jugador>
  </plantilla>
</horario>
