=== Llorens1982/ASIR/1º Lenguajes de marcas y sistemas de gestión de información/Tema 3 XML XSD (XML Schema)/13_Q_Marcas_Salvador_Garcia_Montoro/receptes/receptes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:annotation>
	 <xs:documentation>
	 	Esqueleto del xsd...
	 	xs:schema
	 	xmlns:xs="http://www.w3.org/2001/XMLSchema"	/URI no coincide con la del xml

	 	==============
	 	Elemento simple solo texto, todos los demas son complejos (attr, hijos, mixto)

	 	===============


	 </xs:documentation>	
</xs:annotation>

<!--
receptes es complejo porque tiene hijos
-->	
	<xs:element name="receptes">
		<xs:complexType>
		<xs:sequence>	
			<xs:element name="recepta" minOccurs="1" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="nom" type="xs:string"/>
						<xs:element name="fotografia" minOccurs="0" type="xs:string"/>
						<xs:element name="ingredients">
							<xs:complexType>
							<xs:sequence minOccurs="1" maxOccurs="unbounded">	
							 	<xs:element name="ingredient"  type="xs:string"/>	
							</xs:sequence> 
							</xs:complexType>	
						</xs:element>
						<xs:element name="preparacio">
							<xs:complexType>
								<xs:sequence minOccurs="1" maxOccurs="unbounded">	
								<xs:element name="pas">
									<xs:complexType>
										<xs:simpleContent>
											<xs:extension base="xs:string">
												<xs:attribute name="numero" type="xs:string" use="required"/>
											</xs:extension>	
										</xs:simpleContent>	
									</xs:complexType>	
								</xs:element>
								</xs:sequence>		
							</xs:complexType>	
						</xs:element>	
					</xs:sequence>	
				</xs:complexType>	
			</xs:element>	
		</xs:sequence>	
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Llorens1982/ASIR/1º Lenguajes de marcas y sistemas de gestión de información/Tema 3 XML XSD (XML Schema)/13_Q_Marcas_Salvador_Garcia_Montoro/receptes/receptes.xml
<?xml version="1.0"?>
<receptes xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" 
 	xs:noNamespaceSchemaLocation="receptes.xsd">

<!-- 
	xmlns="http://www.w3schools.com" 
	xmlns:xs= "http://www.w3.org/2001/XMLSchema-instance"  
	xs:schemaLocation="receptes.xsd">
--> 
	<recepta>
		<nom>Patates Fregides</nom>
		<fotografia>patates.png</fotografia>
		<ingredients>
			<ingredient>Oli</ingredient>
			<ingredient>Patates</ingredient>
				<ingredient>Sal</ingredient>
		</ingredients>
		<preparacio>
			<pas numero="1">Es posa l'oli a escalfar</pas>
			<pas numero="2">Mentrestant pelen i tallen les patates</pas>
			<pas numero="3">Quan l'oli estigui ben calent es posen les patates dins de l'oli</pas>
			<pas numero="4">Quan les patates agafin el color desitjat es retiren de l'oli</pas>
			<pas numero="5">Opcionalment es poden posar les patates sobre un paper absorbent</pas>
			<pas numero="6">Abans de servir s'espolvoreigen amb sal</pas>
		</preparacio>
	</recepta>
	<recepta>
		<nom>Arròs negre</nom>
		<ingredients>
			<ingredient>Sipions</ingredient>
			<ingredient>Arròs</ingredient>
			<ingredient>Ceba</ingredient>
			<ingredient>Tomàquet</ingredient>
			<ingredient>Alls</ingredient>
			<ingredient>Pebrot tendre</ingredient>
			<ingredient>Aigua</ingredient>
			<ingredient>Oli</ingredient>
			<ingredient>Sal</ingredient>
		</ingredients>
	<preparacio>
		<pas numero="1">Es pica bé la ceba i es posa a sofregir, en una cassola amb oli i un pessic de sal,
		a poc foc, remenant-la bastant sovint per a què no es cremi</pas>
		<pas numero="2">Quan la ceba quedi ben fosca s'hi afegeixen unes dents d'all, una mica de pebrot tendre,
		també picat ben fi i una bona quantitat de sipions.</pas>
		<pas numero="3">S'hi dóna una remenada i es pica una mica de tomàquet, que també es tira a la cassola.
		Es va remenant per a què els sipions vagin deixant anar la mascara.</pas>
		<pas numero="4">Quan el sofregit està ben lligat, s'hi tira l'arròs i la sal, i se li fa donar un volt o dos</pas>
		<pas numero="5">Després s'hi tira l'aigua bullint.</pas>
		<pas numero="6">Es deixa coure divuit minuts.</pas>
		<pas numero="7">Quan faltin un parell de minuts, s'hi tiren uns alls picats al morter i deixatats en una cullerada d'oli.</pas>
	</preparacio>
	</recepta>
</receptes>
