=== Llorens1982/ASIR/1º Lenguajes de marcas y sistemas de gestión de información/LDM_Examen_Trimestre_3/XSD/alumnes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:element name="alumnes">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="alumne" type="tipoAlumne" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="institut" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  

    <xs:complexType name="tipoAlumne">
      <xs:sequence>
        <xs:element name="nom" type="xs:string"/>
        <xs:element name="cognom" type="xs:string" minOccurs="1" maxOccurs="2"/>
        <xs:element name="Edat" type="xs:integer"/>
        <xs:element name="adreca" type="tipoAdreca"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:string"/>
      <xs:attribute name="cicle" type="tipoCicle"/>
    </xs:complexType>


    <xs:complexType name="tipoAdreca">
      <xs:sequence>
        <xs:element name="ciutat" type="xs:string"/>
        <xs:element name="carrer" type="xs:string"/>
        <xs:element name="numero" type="tipoNumero"/>
        <xs:element name="pis" type="xs:integer"/>
        <xs:element name="porta" type="xs:integer"/>
        <xs:element name="cp" type="xs:integer"/>
      </xs:sequence>
    </xs:complexType>

  
  <xs:simpleType name="tipoCicle">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ASIX"/>
      <xs:enumeration value="SMX"/>
      <xs:enumeration value="DAW"/>
      <xs:enumeration value="DAM"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="tipoNumero">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="1"/>
      <xs:maxInclusive value="200"/>
    </xs:restriction>
  </xs:simpleType>
  
</xs:schema>

=== Llorens1982/ASIR/1º Lenguajes de marcas y sistemas de gestión de información/EXAMENLENGUAJE/XSD/alumnes.xml
<alumnes institut="IES Camp de Morvedre"xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="alumnes.xsd">
	<alumne id="e3542905" cicle="SMX">
	<nom>Juan</nom>
	<cognom>Perez</cognom>
	<cognom>Mohedano</cognom>
	<Edat>27</Edat>
	<adreca>
		<ciutat>Castelló</ciutat>
		<carrer>Pstg. Dos de Mayo</carrer>
		<numero>2</numero>
		<pis>4</pis>
		<porta>1</porta>
		<cp>08440</cp>
	</adreca>
	</alumne>
	<alumne id="h8492401" cicle="DAW">
	<nom>Sergi</nom>
	<cognom>Martí</cognom>
	<Edat>27</Edat>
	<adreca>
		<ciutat>València</ciutat>
		<carrer>Rue del Percebe</carrer>
		<numero>13</numero>
		<pis>1</pis>
		<porta>1</porta>
		<cp>08000</cp>
		</adreca>
	</alumne>
</alumnes>
