=== Llorens1982/ASIR/1º Lenguajes de marcas y sistemas de gestión de información/exemplesTutoriaXML/pedido.dtd
<!ELEMENT pedido (producto+)>
<!ELEMENT producto (referencia,unidades,color?)>
<!ELEMENT referencia (#PCDATA)>

<!ELEMENT unidades (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ATTLIST pedido fecha CDATA  #REQUIRED>
<!ATTLIST color codigo CDATA  #REQUIRED>
<!ATTLIST producto talla (L|M|XL|S) #REQUIRED>

=== Llorens1982/ASIR/1º Lenguajes de marcas y sistemas de gestión de información/exemplesTutoriaXML/pedido 2.xml
<!DOCTYPE pedido SYSTEM "pedido.dtd">
<pedido fecha="2019-01-01">
          <producto talla="L">
          <referencia>A-123</referencia>        
          <unidades>3</unidades>
          <color codigo="43">Rojo</color>
        </producto>
        <producto talla="M">
          <referencia>A-123</referencia>        
          <unidades>3</unidades>
        </producto>
        <producto talla="XL">
          <referencia>B-123</referencia>        
          <unidades>3</unidades>
        </producto>
  
</pedido>
