=== Llorens1982/ASIR/1º Lenguajes de marcas y sistemas de gestión de información/EXAMEN EXTRAODINARIO/XSD/plantilla.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="domicilio">
    <xs:complexType>
      <xs:simpleType>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:int" name="cod_postal" use="optional"/>
        </xs:extension>
      </xs:simpleType>
    </xs:complexType>
  </xs:element>
  <xs:element name="provincia" type="xs:string"/>
  <xs:element name="nombre" type="xs:string"/>
  <xs:element name="apellidos" type="xs:string"/>
  <xs:element name="direccion">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="domicilio"/>
        <xs:element ref="provincia"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="jugador">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nombre"/>
        <xs:element ref="apellidos"/>
        <xs:element ref="direccion"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="id"/>
      <xs:attribute type="xs:string" name="posicion"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="plantilla">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="jugador" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Llorens1982/ASIR/1º Lenguajes de marcas y sistemas de gestión de información/EXAMEN EXTRAODINARIO/XSD/plantilla.xml
<?xml version="1.0" encoding="UTF-8"?>
<plantilla xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="plantilla.xsd">>
  <jugador id="J001" posicion="portero">
    <nombre>Jose Ramón</nombre>
    <apellidos>García González</apellidos>
    <direccion>
      <domicilio cod_postal="46003">El Pez, 12</domicilio>
      <provincia>Cantabria</provincia>
    </direccion>
  </jugador>
  <jugador id="J005" posicion="delantero">
    <nombre>Carlos</nombre>
    <apellidos>López Pérez</apellidos>
    <direccion>
      <domicilio cod_postal="46025">El Cangrejo, 25</domicilio>
      <provincia>Cantabria</provincia>
    </direccion>
  </jugador>
</plantilla>
